version: '3.8'

services:
  no-excuse:
    build: .
    container_name: no-excuse
    restart: always
    ports:
      - "80:80"
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
